#!/bin/bash
#
# Setup networking for Vast.ai instances to join the RingRift P2P cluster
#
# This script:
# 1. Installs Tailscale for encrypted mesh networking
# 2. Joins the Tailscale network with an auth key
# 3. Sets up the P2P coordinator endpoint
# 4. Syncs the RingRift codebase
#
# Usage:
#   # From local machine, run on a single instance:
#   ssh root@ssh5.vast.ai -p 14364 "bash -s" < scripts/setup_vast_networking.sh
#
#   # Or run on all instances:
#   for port in 14364 14370 14398 14400 19766 19768 19940 19942 19942 10012 10014 17016; do
#     echo "=== Setting up instance on port $port ==="
#     ssh -o ConnectTimeout=10 root@ssh5.vast.ai -p $port "bash -s" < scripts/setup_vast_networking.sh || true
#   done
#
# Environment variables (set before running or hard-code below):
#   TAILSCALE_AUTH_KEY - Tailscale auth key for joining network
#   P2P_LEADER_URL     - URL of the P2P leader node

set -e

echo "=== RingRift Vast Instance Setup ==="

# Configuration (set these or pass as env vars)
TAILSCALE_AUTH_KEY="${TAILSCALE_AUTH_KEY:-}"
P2P_LEADER_URL="${P2P_LEADER_URL:-http://209.20.157.81:8765}"  # H100 default
RINGRIFT_REPO="https://github.com/an0mium/RingRift.git"
RINGRIFT_DIR="$HOME/ringrift"

# Detect if we're on Vast.ai (look for vast-specific markers)
IS_VAST=false
if [ -f /etc/motd ] && grep -q "vast" /etc/motd 2>/dev/null; then
    IS_VAST=true
fi

echo "Host: $(hostname)"
echo "Is Vast: $IS_VAST"
echo "P2P Leader: $P2P_LEADER_URL"

# ============================================
# Step 1: Install Tailscale
# ============================================
install_tailscale() {
    echo ""
    echo "=== Installing Tailscale ==="

    if command -v tailscale &> /dev/null; then
        echo "Tailscale already installed"
        return 0
    fi

    # Install Tailscale
    curl -fsSL https://tailscale.com/install.sh | sh

    # Enable and start the service
    if command -v systemctl &> /dev/null; then
        systemctl enable --now tailscaled
    fi

    echo "Tailscale installed successfully"
}

# ============================================
# Step 2: Join Tailscale Network
# ============================================
join_tailscale() {
    echo ""
    echo "=== Joining Tailscale Network ==="

    if [ -z "$TAILSCALE_AUTH_KEY" ]; then
        echo "WARNING: TAILSCALE_AUTH_KEY not set"
        echo "To join the network, run:"
        echo "  tailscale up --authkey=YOUR_AUTH_KEY --hostname=$(hostname)"
        return 1
    fi

    # Check if already connected
    if tailscale status 2>/dev/null | grep -q "100\."; then
        echo "Already connected to Tailscale"
        tailscale status | head -5
        return 0
    fi

    # Join with auth key
    tailscale up --authkey="$TAILSCALE_AUTH_KEY" --hostname="vast-$(hostname | cut -c1-8)"

    echo "Joined Tailscale network"
    tailscale status | head -5
}

# ============================================
# Step 3: Sync RingRift Codebase
# ============================================
sync_ringrift() {
    echo ""
    echo "=== Syncing RingRift Codebase ==="

    if [ ! -d "$RINGRIFT_DIR" ]; then
        echo "Cloning RingRift repository..."
        git clone --depth=1 "$RINGRIFT_REPO" "$RINGRIFT_DIR"
    else
        echo "Updating existing repository..."
        cd "$RINGRIFT_DIR"
        git fetch origin main
        git reset --hard origin/main
    fi

    # Setup Python environment
    cd "$RINGRIFT_DIR/ai-service"
    if [ ! -d "venv" ]; then
        echo "Creating Python virtual environment..."
        python3 -m venv venv
    fi

    echo "Installing dependencies..."
    source venv/bin/activate
    pip install --upgrade pip -q
    pip install -r requirements.txt -q 2>/dev/null || true

    echo "RingRift synced to $(cd $RINGRIFT_DIR && git rev-parse --short HEAD)"
}

# ============================================
# Step 4: Configure P2P Settings
# ============================================
configure_p2p() {
    echo ""
    echo "=== Configuring P2P Settings ==="

    # Set environment variables for P2P
    P2P_ENV_FILE="$RINGRIFT_DIR/ai-service/.env.p2p"

    cat > "$P2P_ENV_FILE" << EOF
# P2P Configuration (auto-generated by setup script)
RINGRIFT_P2P_LEADER_URL=$P2P_LEADER_URL
RINGRIFT_P2P_SEEDS=$P2P_LEADER_URL
RINGRIFT_NODE_ID=vast-$(hostname | cut -c1-8)
RINGRIFT_SKIP_SHADOW_CONTRACTS=true
EOF

    echo "P2P config written to $P2P_ENV_FILE"
}

# ============================================
# Step 5: Test Connectivity
# ============================================
test_connectivity() {
    echo ""
    echo "=== Testing Connectivity ==="

    # Test P2P leader
    echo "Testing P2P leader at $P2P_LEADER_URL..."
    if curl -s --connect-timeout 5 "$P2P_LEADER_URL/health" > /dev/null 2>&1; then
        echo "  P2P leader: OK"
    else
        echo "  P2P leader: UNREACHABLE (will retry via Tailscale)"
    fi

    # Test Tailscale connectivity
    if command -v tailscale &> /dev/null; then
        echo ""
        echo "Tailscale peers:"
        tailscale status | grep -E "^100\." | head -10 || echo "  No peers visible yet"
    fi
}

# ============================================
# Step 6: Register with P2P Coordinator
# ============================================
register_with_p2p() {
    echo ""
    echo "=== Registering with P2P Coordinator ==="

    # Get Tailscale IP if available
    TS_IP=$(tailscale ip -4 2>/dev/null || echo "")

    # Get GPU info
    GPU_NAME=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || echo "Unknown")
    GPU_MEM=$(nvidia-smi --query-gpu=memory.total --format=csv,noheader 2>/dev/null | head -1 || echo "0 MiB")

    # Build registration payload
    PAYLOAD=$(cat << EOF
{
    "node_id": "vast-$(hostname | cut -c1-8)",
    "tailscale_ip": "$TS_IP",
    "gpu_name": "$GPU_NAME",
    "gpu_memory": "$GPU_MEM",
    "capabilities": ["selfplay", "evaluation"],
    "status": "available"
}
EOF
)

    echo "Registration payload:"
    echo "$PAYLOAD" | python3 -m json.tool 2>/dev/null || echo "$PAYLOAD"

    # Try to register (non-blocking)
    if [ -n "$TS_IP" ]; then
        echo "Would register with P2P at $P2P_LEADER_URL/api/v1/nodes/register"
        # curl -X POST "$P2P_LEADER_URL/api/v1/nodes/register" \
        #     -H "Content-Type: application/json" \
        #     -d "$PAYLOAD" 2>/dev/null || true
    fi
}

# ============================================
# Main
# ============================================
main() {
    # Step 1: Install Tailscale
    install_tailscale

    # Step 2: Join Tailscale network
    join_tailscale || true  # Don't fail if no auth key

    # Step 3: Sync codebase
    sync_ringrift

    # Step 4: Configure P2P
    configure_p2p

    # Step 5: Test connectivity
    test_connectivity

    # Step 6: Register with P2P
    register_with_p2p

    echo ""
    echo "=== Setup Complete ==="
    echo "Node: vast-$(hostname | cut -c1-8)"
    echo "Tailscale IP: $(tailscale ip -4 2>/dev/null || echo 'Not connected')"
    echo ""
    echo "To start selfplay, run:"
    echo "  cd $RINGRIFT_DIR/ai-service && source venv/bin/activate"
    echo "  PYTHONPATH=. python scripts/run_gpu_selfplay.py --board square8 --num-players 2 --num-games 100"
}

main "$@"
